### ISSUE TITLE
"Error: Comment not terminated"

### ISSUE THREAD

**Issue by Fourchaux** [LesleyLai/ocamlpt#1]
Quick tip for 'let mult v1 s = ...' :

"Error: Comment not terminated" is a "classical" trap in OCaml. 
It's because comments are introduced by the two characters (* .  

The solution is to put a -space- between ( and * 
```ocaml
let ( *| ) v1 s = ...
```

**Comment by LesleyLai** [comment]
Thank you for the tip! I will fix it.
